# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0002_pictureitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureitem',
            old_name='created_on',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='pictureitem',
            name='picture',
            field=models.ImageField(default='', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
