# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0003_auto_20180806_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grading_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank_me_api.PictureItem')),
            ],
        ),
    ]
