# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0004_gradeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeitem',
            name='picture',
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='grade',
            field=models.CharField(max_length=255),
        ),
    ]
