# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0006_auto_20180830_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeitem',
            old_name='user_profile',
            new_name='grading_user_id',
        ),
    ]
