# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0007_auto_20180830_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeitem',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rank_me_api.PictureItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
