# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0008_auto_20180830_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='not specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_profile_picture',
            field=models.ForeignKey(default=-99, on_delete=django.db.models.deletion.CASCADE, to='rank_me_api.PictureItem'),
            preserve_default=False,
        ),
    ]
