# Generated by Django 2.1.1 on 2018-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0010_auto_20180901_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeitem',
            name='picture',
            field=models.ForeignKey(on_delete=None, to='rank_me_api.PictureItem'),
        ),
    ]
