# Generated by Django 2.1.1 on 2018-09-19 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0011_auto_20180918_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeitem',
            name='grading_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank_me_api.PictureItem'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='main_profile_picture',
            field=models.ForeignKey(blank=True, default='Null', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rank_me_api.PictureItem'),
        ),
    ]
