# Generated by Django 2.1.1 on 2018-09-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0012_auto_20180919_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='main_profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank_me_api.PictureItem'),
        ),
    ]
