# Generated by Django 2.1.1 on 2018-09-21 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0014_gradeitem_status_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeitem',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='pictureitem',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='grading_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='status_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pictureitem',
            name='status_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
