# Generated by Django 2.1.1 on 2018-09-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0015_auto_20180921_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeitem',
            old_name='grading_user_id',
            new_name='grading_user',
        ),
    ]
