# Generated by Django 2.1.1 on 2018-09-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0016_auto_20180923_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureitem',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
