# Generated by Django 2.1.1 on 2018-09-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_me_api', '0017_auto_20180924_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeitem',
            old_name='grading_user',
            new_name='grading_profile',
        ),
    ]
